### ISSUE TITLE
support for file:///path/to/file needed

### ISSUE THREAD

**Issue by reikred** [EuanRiggans/BulkURLOpener-Firefox#1]
I could not get the addon to open URLs of the type file:///path/to/file, which is what I need it for :).

Maybe an easy fix?

UPDATE: I made simple but perhaps sufficient hack and created a pull request. Please evaluate and merge if ok!

Note to self: The addon somehow did not recognize file:///path/to/file and created a tab with a google search for "file:///path/to/file" instead.

**Comment by EuanRiggans** [comment]
Thanks for letting me know about this, and thanks for submitting the pull request :)

**Comment by EuanRiggans** [comment]
> 
> 
> I could not get the addon to open URLs of the type file:///path/to/file, which is what I need it for :).
> 
> Maybe an easy fix?
> 
> UPDATE: I made simple but perhaps sufficient hack and created a pull request. Please evaluate and merge if ok!
> 
> Note to self: The addon somehow did not recognize file:///path/to/file and created a tab with a google search for "file:///path/to/file" instead.

I did some research and it seems that Firefox does not allow scripts to open file: and about: urls. So unfortunatley I don't think it will be possible to open these links in the addon.
